name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Start Firebase Emulators
      run: firebase emulators:start --only firestore --project demo-project &
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    # Wait for emulators to fully start
    - name: Wait for emulators
      run: sleep 10s
      
    - name: Run Unit Tests
      run: ./gradlew test
      
    - name: Run Instrumentation Tests with Firebase Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedAndroidTest
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          app/build/reports/tests/
          app/build/reports/androidTests/connected/
